# This is a basic workflow to help you get started with Actions

name: corne

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Prerequisites
        run: sudo apt-get install -y git python3-pip python3-setuptools
      # Runs a set of commands using the runners shell
      - name: install qmk cli
        run: sudo python3 -m pip install --user qmk        
      - name: Update path to include local bin, ubuntu has a bug 
        run: echo 'PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc && source $HOME/.bashrc       
      - name: chmod 
        run: sudo chmod +x $HOME/.local/bin/qmk
      - name: Link custom keymap definition
        run: ln -s $(pwd)/snazzy-boi $(pwd)/qmk_firmware/keyboards/crkbd/keymaps/snazzy-boi
      - name: setup 
        run: sudo $HOME/.local/bin/qmk compile -kb crkbd/rev1/common -km snazzy-boi   
      - uses: actions/upload-artifact@v2
        with:
          name: corne-snazzy-boi-default.hex
          path: ~/qmk_firmware/crkbd_rev1_common_snazzy-boi.hex
      - name: Release
        uses: docker://softprops/action-gh-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: qmk_firmware/crkbd_rev1_common_snazzy-boi.hex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
